<?php

namespace Database\Seeders;

use App\Models\WeddingTemplate;
use Illuminate\Database\Seeder;

class WeddingTemplateSeeder extends Seeder
{
    public function run(): void
    {
        WeddingTemplate::updateOrCreate(
            ['slug' => 'vintage-romance'],
            [
                'name' => 'Vintage Romance',
                'description' => 'Template undangan pernikahan dengan nuansa vintage yang elegan.',
                'thumbnail' => 'assets/vintage/vendor/PAPER-BG-FLORAL-Q.jpg',
                'is_active' => true,
                'sections_config' => [
                    'enabled' => [
                        'hero' => true,
                        'couple' => true,
                        'story' => true,
                        'events' => true,
                        'gallery' => true,
                        'countdown' => true,
                        'gift' => true,
                        'rsvp' => true,
                        'live' => true,
                        'dresscode' => true,
                        'best_wishes' => true,
                        'thanks' => true,
                    ],
                    'order' => [
                        'hero',
                        'couple',
                        'story',
                        'events',
                        'gallery',
                        'countdown',
                        'gift',
                        'rsvp',
                        'live',
                        'dresscode',
                        'best_wishes',
                        'thanks',
                    ],
                ],
                'styling_config' => [
                    'primary_color' => '#8B7355',
                    'secondary_color' => '#D4C5A9',
                    'font_heading' => 'Caudex',
                    'font_body' => 'Catamaran',
                    'background_style' => 'floral',
                ],
                'assets_config' => [
                    'groom_photo' => 'template-assets/vintage-romance/std06424-1789712199.jpg',
                    'hero_photo' => 'template-assets/vintage-romance/std06350-1789712351.jpg',
                    'story_image' => 'template-assets/vintage-romance/std06393-1789712370.jpg',
                    'desktop_cover' => 'template-assets/vintage-romance/std06393-1789712430.jpg',
                    'closing_image' => 'template-assets/vintage-romance/std06183-1789721336.jpg',
                    'logo_image' => 'template-assets/vintage-romance/td-logo-1-1-1789712466.png',
                    'bg_slide_1' => 'template-assets/vintage-romance/std06393-1789712490.jpg',
                    'bg_slide_2' => 'template-assets/vintage-romance/std06544-1789712498.jpg',
                    'bride_photo' => 'template-assets/vintage-romance/std06429-1789715960.jpg',
                    'gift_logo_gift-1789716913080' => 'template-assets/vintage-romance/screenshot-2026-09-18-at-144642-1789717612.png',
                    'gift_logo_gift-1789717292825' => 'template-assets/vintage-romance/screenshot-2026-09-18-at-144309-1789717398.png',
                    'backsound_file' => 'template-assets/vintage-romance/saxophone-dreamsound-a-whole-new-world-aladdin-s-theme-mp3pm-1789718601.mp3',
                    'gift_logo_gift-1789720180719' => 'template-assets/vintage-romance/screenshot-2026-09-18-at-153058-1789720272.png',
                ],
                'gallery' => [
                    ['path' => 'template-assets/vintage-romance/gallery/std06544-1789712543-9.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06491-1789712543-8.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06565-1789712543-11.jpg', 'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06562-1789712543-10.jpg', 'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06575-1789712543-12.jpg', 'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06625-1789712543-13.jpg', 'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06473-1789712543-7.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06183-1789712543-1.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06263-1789712543-2.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06165-1789712543-0.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06310-1789712543-3.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06337-1789712543-4.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06350-1789712543-5.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                    ['path' => 'template-assets/vintage-romance/gallery/std06393-1789712543-6.jpg',  'caption' => null, 'created_at' => '2026-09-18 06:22:23'],
                ],
                'template_settings' => [
                    'bride_name' => 'Tusi',
                    'groom_name' => 'Didik',
                    'bride_full_name' => 'Tusiarti Handayani',
                    'groom_full_name' => 'Didik Wahyudin',
                    'bride_father' => 'Subarno',
                    'bride_mother' => 'Ruminem',
                    'groom_father' => 'Mujiono',
                    'groom_mother' => 'Mujiatin',
                    'bride_instagram' => '',
                    'groom_instagram' => '',
                    'couple_subtitle' => 'Bride & Groom',
                    'hero_subtitle' => 'a journey of love begins',
                    'hero_title' => 'THE WEDDING OF',
                    'hero_verse' => '"Di antara tanda-tanda (kebesaran)-Nya ialah bahwa Dia menciptakan pasangan-pasangan untukmu dari (jenis) dirimu sendiri agar kamu merasa tenteram kepadanya. Dia menjadikan di antaramu rasa cinta dan kasih sayang. Sesungguhnya pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir."',
                    'hero_verse_source' => '(Q.S Ar-rum 21)',
                    'story_title' => 'Our Story',
                    'story_subtitle' => 'Every love story is beautiful but ours is my favorite',
                    'gallery_title' => 'The Moments of',
                    'gallery_subtitle' => '',
                    'countdown_title' => 'Counting The Days',
                    'wedding_day_title' => 'Wedding Day',
                    'wedding_day_subtitle' => 'InsyaAllah akan dilaksanakan pada:',
                    'event_akad_title' => 'Akad Nikah',
                    'event_resepsi_title' => 'Resepsi Pernikahan',
                    'rsvp_title' => 'Konfirmasi Kehadiran',
                    'rsvp_subtitle' => 'Mohon konfirmasi kehadiran Bapak/Ibu/Saudara/i',
                    'gift_title' => 'Wedding Gift',
                    'gift_subtitle' => 'Doa restu Anda merupakan karunia yang sangat berarti bagi kami. Namun jika Bapak/Ibu ingin memberikan tanda kasih, kami telah menyediakan fitur berikut:',
                    'thank_title' => 'Terima Kasih',
                    'thank_text' => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Anda berkenan hadir dan memberikan doa restunya untuk pernikahan kami.',
                    'thank_closing' => 'Atas doa & restunya, kami ucapkan terima kasih.',
                    'footer_message' => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu kepada kami.',
                    'wassalam_text' => "Wassalamu'alaikum Warahmatullahi Wabarakatuh",
                    'live_stream_url' => '',
                    'show_bride_photo' => '1',
                    'show_groom_photo' => '1',
                    'show_story_image' => '1',
                    'show_gallery' => '1',
                    'show_countdown' => '1',
                    'show_gift' => '1',
                    'show_live' => '0',
                    'show_dresscode' => '0',
                    'show_story' => '1',
                    'show_best_wishes' => '1',
                    'show_footer' => '0',
                    'backsound' => 'custom',
                    'story_items' => [
                        [
                            'title' => 'Asmaraloka',
                            'description' => "Tidak semua awal perlu diceritakan panjang, \nkarena yang bertahan akan selalu menemukan jalannya.\n\nBukan karena semuanya sempurna, \nmelainkan karena kami terus belajar untuk tumbuh bersama.",
                        ],
                        [
                            'title' => '',
                            'description' => "Kami percaya, tidak ada pertemuan yang benar-benar kebetulan, \nada doa yang diam-diam dikabulkan, dan ada langkah yang diarahkan tanpa kita sadari. \n\nDan Allah SWT, dengan cara-Nya yang paling tenang, \nmenuntun kami sampai di titik ini.",
                        ],
                        [
                            'title' => '',
                            'description' => "Hingga pada waktunya, \nsegala yang telah kami lewati bermuara pada satu keputusan yang sama. \n\nDengan penuh syukur, \nkami memilih untuk saling menetap dalam ikatan yang di ridhoi oleh-Nya.\n\nSemoga perjalanan ini selalu diliputi ketenangan, \nkebahagiaan, dan dipelihara dalam kebaikan yang panjang.",
                        ],
                    ],
                    // SEO settings
                    'seo_meta_title' => '',
                    'seo_meta_description' => '',
                    'seo_og_title' => '',
                    'seo_og_description' => '',
                    'seo_og_image_asset' => 'cover_photo',
                ],
                'gifts' => [
                    [
                        'id' => 'gift-1789716913080',
                        'type' => 'bank',
                        'label' => 'Bank BCA',
                        'number' => '2910557010',
                        'holder' => 'Tusiarti Handayani',
                        'address' => '',
                        'default_logo' => null,
                    ],
                    [
                        'id' => 'gift-1789717292825',
                        'type' => 'bank',
                        'label' => 'Bank Danamon',
                        'number' => '903687549919',
                        'holder' => 'Tusiarti Handayani',
                        'address' => '',
                        'default_logo' => null,
                    ],
                    [
                        'id' => 'gift-1789720180719',
                        'type' => 'bank',
                        'label' => 'Neobank',
                        'number' => '5859459283848074',
                        'holder' => 'Tusiarti Handayani',
                        'address' => '',
                        'default_logo' => null,
                    ],
                ],
            ]
        );

        $this->command->info('✅ Vintage Romance template seeded.');
    }
}