services:
    db:
        image: mysql:latest
        container_name: db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wedding
        volumes:
            - ./volume/db:/var/lib/mysql
